// GENERATED by scripts/gen-meta.mjs — safe to edit by hand, but a re-run
// preserves entries and only regenerates routes that fail the spec.
//
// Fallback meta for routes with no hand-written entry in the SERVICE_META /
// LOCATION_META / POST_META maps in ./seo.ts. Review before committing.
export const GENERATED_META: Record<string, { title: string; description: string }> = {}
